# Vehicles Analisys

## Introduction

In this project, the vehicles_us.csv dataset will be analyzed through an **Exploratory Data Analysis** (EDA) process to identify patterns, trends, and key characteristics of used **vehicle listings** in the United States. 

The analysis will focus on understanding the structure and quality of the data, identifying missing values and inconsistencies, creating new features to enrich the dataset, and exploring relationships between variables that may influence vehicle prices and market behavior. Through descriptive statistics and visualizations, the project aims to provide actionable insights into the used vehicle market and the factors associated with vehicle value.

The project will be divided into the following stages:

1. Data Collection and Initial Exploration
2. Data Cleaning and Correction
3. Data Enrichment
4. Exploratory Data Analysis
5. Conclusions.

The insights and results generated throughout this analysis will be **integrated** into an interactive **web application** developed with Streamlit and deployed on Render. This platform will allow users to explore the dataset dynamically through **visualizations**, **filters**, and statistical summaries, providing an accessible and user-friendly way to interact with the information. By leveraging an interactive interface, users will be able to gain a deeper understanding of vehicle market trends, compare different vehicle characteristics, and discover data-driven insights without requiring any prior knowledge of data analysis tools.

## 1. Data Collection and Initial Exploration

In [27]:
# Import libraries
import pandas as pd
import seaborn as sns
import plotly.graph_objects as go
import plotly.express as px
import os
from pathlib import Path # library to handle file paths
#py -m pip install nbformat

In [2]:
# Load the dataset
vehicles_df = pd.read_csv('../vehicles_us.csv')

vehicles_df.head()

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
0,9400,2011.0,bmw x5,good,6.0,gas,145000.0,automatic,SUV,NaN,1.0,2018-06-23,19
1,25500,NaN,ford f-150,good,6.0,gas,88705.0,automatic,pickup,white,1.0,2018-10-19,50
2,5500,2013.0,hyundai sonata,like new,4.0,gas,110000.0,automatic,sedan,red,NaN,2019-02-07,79
3,1500,2003.0,ford f-150,fair,8.0,gas,NaN,automatic,pickup,NaN,NaN,2019-03-22,9
4,14900,2017.0,chrysler 200,excellent,4.0,gas,80903.0,automatic,sedan,black,NaN,2019-04-02,28

In [3]:
# Information about the dataset
vehicles_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         51525 non-null  int64
 1   model_year    47906 non-null  float64
 2   model         51525 non-null  str
 3   condition     51525 non-null  str
 4   cylinders     46265 non-null  float64
 5   fuel          51525 non-null  str
 6   odometer      43633 non-null  float64
 7   transmission  51525 non-null  str
 8   type          51525 non-null  str
 9   paint_color   42258 non-null  str
 10  is_4wd        25572 non-null  float64
 11  date_posted   51525 non-null  str
 12  days_listed   51525 non-null  int64
dtypes: float64(4), int64(2), str(7)
memory usage: 5.1 MB

## 2. Data Cleaning and Correction

In [4]:
# Replace missing values in 'paint_color' with 'Unknown'
vehicles_df['paint_color'] = vehicles_df['paint_color'].fillna('Unknown')

# Replace missing values in 'is_4wd' with 0
vehicles_df['is_4wd'] = vehicles_df['is_4wd'].fillna(0)

# Convert 'is_4wd' to integer type
vehicles_df['is_4wd'] = vehicles_df['is_4wd'].astype(int)

# Change the data type of 'date_posted' to datetime
vehicles_df['date_posted'] = pd.to_datetime(vehicles_df['date_posted'])

vehicles_df.head()

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
0,9400,2011.0,bmw x5,good,6.0,gas,145000.0,automatic,SUV,Unknown,1,2018-06-23,19
1,25500,NaN,ford f-150,good,6.0,gas,88705.0,automatic,pickup,white,1,2018-10-19,50
2,5500,2013.0,hyundai sonata,like new,4.0,gas,110000.0,automatic,sedan,red,0,2019-02-07,79
3,1500,2003.0,ford f-150,fair,8.0,gas,NaN,automatic,pickup,Unknown,0,2019-03-22,9
4,14900,2017.0,chrysler 200,excellent,4.0,gas,80903.0,automatic,sedan,black,0,2019-04-02,28

In [5]:
# Verify the changes made to the dataset
vehicles_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         51525 non-null  int64
 1   model_year    47906 non-null  float64
 2   model         51525 non-null  str
 3   condition     51525 non-null  str
 4   cylinders     46265 non-null  float64
 5   fuel          51525 non-null  str
 6   odometer      43633 non-null  float64
 7   transmission  51525 non-null  str
 8   type          51525 non-null  str
 9   paint_color   51525 non-null  str
 10  is_4wd        51525 non-null  int64
 11  date_posted   51525 non-null  datetime64[us]
 12  days_listed   51525 non-null  int64
dtypes: datetime64[us](1), float64(3), int64(3), str(6)
memory usage: 5.1 MB

In [6]:
# Verify if there are duplicates
print(vehicles_df.duplicated().sum(), "duplicates found in the dataset.")

0 duplicates found in the dataset.

In [7]:
# Implicitly duplicates in 'model' column
sorted(vehicles_df['model'].unique())

['acura tl',
 'bmw x5',
 'buick enclave',
 'cadillac escalade',
 'chevrolet camaro',
 'chevrolet camaro lt coupe 2d',
 'chevrolet colorado',
 'chevrolet corvette',
 'chevrolet cruze',
 'chevrolet equinox',
 'chevrolet impala',
 'chevrolet malibu',
 'chevrolet silverado',
 'chevrolet silverado 1500',
 'chevrolet silverado 1500 crew',
 'chevrolet silverado 2500hd',
 'chevrolet silverado 3500hd',
 'chevrolet suburban',
 'chevrolet tahoe',
 'chevrolet trailblazer',
 'chevrolet traverse',
 'chrysler 200',
 'chrysler 300',
 'chrysler town & country',
 'dodge charger',
 'dodge dakota',
 'dodge grand caravan',
 'ford econoline',
 'ford edge',
 'ford escape',
 'ford expedition',
 'ford explorer',
 'ford f-150',
 'ford f-250',
 'ford f-250 sd',
 'ford f-250 super duty',
 'ford f-350 sd',
 'ford f150',
 'ford f150 supercrew cab xlt',
 'ford f250',
 'ford f250 super duty',
 'ford f350',
 'ford f350 super duty',
 'ford focus',
 'ford focus se',
 'ford fusion',
 'ford fusion se',
 'ford mustang',
 'ford mustang gt coupe 2d',
 'ford ranger',
 'ford taurus',
 'gmc acadia',
 'gmc sierra',
 'gmc sierra 1500',
 'gmc sierra 2500hd',
 'gmc yukon',
 'honda accord',
 'honda civic',
 'honda civic lx',
 'honda cr-v',
 'honda odyssey',
 'honda pilot',
 'hyundai elantra',
 'hyundai santa fe',
 'hyundai sonata',
 'jeep cherokee',
 'jeep grand cherokee',
 'jeep grand cherokee laredo',
 'jeep liberty',
 'jeep wrangler',
 'jeep wrangler unlimited',
 'kia sorento',
 'kia soul',
 'mercedes-benz benze sprinter 2500',
 'nissan altima',
 'nissan frontier',
 'nissan frontier crew cab sv',
 'nissan maxima',
 'nissan murano',
 'nissan rogue',
 'nissan sentra',
 'nissan versa',
 'ram 1500',
 'ram 2500',
 'ram 3500',
 'subaru forester',
 'subaru impreza',
 'subaru outback',
 'toyota 4runner',
 'toyota camry',
 'toyota camry le',
 'toyota corolla',
 'toyota highlander',
 'toyota prius',
 'toyota rav4',
 'toyota sienna',
 'toyota tacoma',
 'toyota tundra',
 'volkswagen jetta',
 'volkswagen passat']

In [8]:
# Remove 'benze' word from 'model' column
vehicles_df['model'] = vehicles_df['model'].str.replace('benze ', '', regex=False)
sorted(vehicles_df['model'].unique())[70:74]

['jeep wrangler unlimited',
 'kia sorento',
 'kia soul',
 'mercedes-benz sprinter 2500']

In [9]:
# Implicitly duplicates in 'condition' column
sorted(vehicles_df['condition'].unique())

['excellent', 'fair', 'good', 'like new', 'new', 'salvage']

In [10]:
# Implicitly duplicates in 'fuel' column
sorted(vehicles_df['fuel'].unique())

['diesel', 'electric', 'gas', 'hybrid', 'other']

In [11]:
# Implicitly duplicates in 'transmission' column
sorted(vehicles_df['transmission'].unique())

['automatic', 'manual', 'other']

In [12]:
# Implicitly duplicates in 'type' column
sorted(vehicles_df['type'].unique())

['SUV',
 'bus',
 'convertible',
 'coupe',
 'hatchback',
 'mini-van',
 'offroad',
 'other',
 'pickup',
 'sedan',
 'truck',
 'van',
 'wagon']

In [13]:
# Convert 'type' in lower case
vehicles_df['type'] = vehicles_df['type'].str.lower()
sorted(vehicles_df['type'].unique())

['bus',
 'convertible',
 'coupe',
 'hatchback',
 'mini-van',
 'offroad',
 'other',
 'pickup',
 'sedan',
 'suv',
 'truck',
 'van',
 'wagon']

In [14]:
# Implicitly duplicates in 'paint_color' column
sorted(vehicles_df['paint_color'].unique())

['Unknown',
 'black',
 'blue',
 'brown',
 'custom',
 'green',
 'grey',
 'orange',
 'purple',
 'red',
 'silver',
 'white',
 'yellow']

## 3. Data Enrichment

In [15]:
# Split Manufacturer and Model into separate columns
vehicles_df[['manufacturer', 'model']] = vehicles_df['model'].str.split(' ', n=1, expand=True)
vehicles_df.head()

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed,manufacturer
0,9400,2011.0,x5,good,6.0,gas,145000.0,automatic,suv,Unknown,1,2018-06-23,19,bmw
1,25500,NaN,f-150,good,6.0,gas,88705.0,automatic,pickup,white,1,2018-10-19,50,ford
2,5500,2013.0,sonata,like new,4.0,gas,110000.0,automatic,sedan,red,0,2019-02-07,79,hyundai
3,1500,2003.0,f-150,fair,8.0,gas,NaN,automatic,pickup,Unknown,0,2019-03-22,9,ford
4,14900,2017.0,200,excellent,4.0,gas,80903.0,automatic,sedan,black,0,2019-04-02,28,chrysler

**Findings**

* **Missing values** in the model_year, cylinders, and odometer columns were **retained.** During subsequent stages of data processing, these records will be filtered as needed to prevent them from affecting calculations while preserving potentially valuable information.

* The **data types** of the columns were reviewed and **corrected** to ensure consistency and support accurate analysis.

* The entry "mercedes-benz benze sprinter 2500" appears to contain a typographical error. While Mercedes-Benz is the vehicle manufacturer and Sprinter 2500 is a recognized model, the term **"benze"** does not correspond to any known Mercedes-Benz model and is likely the result of inconsistent or **erroneous data** entry.

* The model column was split into separate fields because it contained both the **manufacturer** name and the vehicle **model**, allowing for more detailed analysis by brand and model.

* **No** explicit or implicit **duplicate** records were identified in the dataset.

* **Missing values** in the paint_color column were **replaced** with **"Unknown"**, while missing values in the is_4wd column were replaced with **0**, indicating that four-wheel drive was not specified for those records.

## 4. Exploratory Data Analysis

In [45]:
# Vehicles types by manufacturer
manufacturer_type_counts = vehicles_df.groupby(['manufacturer', 'type']).size().reset_index(name='count')

# Order manufacturers by total count
manufacturer_list = manufacturer_type_counts.groupby('manufacturer')['count'].sum().sort_values(ascending=False).index.to_list()

# Create a stacked bar chart using Plotly Express
fig = px.bar(
    manufacturer_type_counts,
    x='manufacturer',
    y='count',
    color='type',
    barmode='stack',
    category_orders={'manufacturer': manufacturer_list},
)

# Title and axis labels
fig.update_layout(
    title='Vehicle Types by Manufacturer',
    xaxis_title='Manufacturer',
    yaxis_title='Count',
    legend_title='Vehicle Type',
    #xaxis_tickangle=-45,
)

fig.show()

In [57]:
# Kilometers vs Price scatter plot
fig = px.scatter(
    vehicles_df[vehicles_df['type'] == 'sedan'],  # Filter outliers for better visualization
    x='odometer',
    y='price',
    title='Kilometers vs Price'
)

# Title and axis labels
fig.update_layout(
    xaxis_title='Odometer (km)',
    yaxis_title='Price ($)',
)

fig.show()

In [ ]:
# Correlation between 'odometer' and 'price' sedan type vehicles
vehicles_df[vehicles_df['type'] == 'sedan'][['odometer', 'price']].corr()

          odometer     price
odometer  1.000000 -0.516501
price    -0.516501  1.000000

In [ ]:
# Histogram of model year by condition
fig = px.histogram(
    vehicles_df,
    x='model_year',
    title='Distribution of Vehicle Years',
    color='condition',
)

# Title and axis labels
fig.update_layout(
    xaxis_title='Model Year',
    yaxis_title='Count',
)

fig.show()